<!DOCTYPE html>
   <html lang="es">
   <head>
     <meta charset="UTF-8">
     <title>TISOL</title>
     <?php include 'inc/head_common.php'; ?>
<!-- Latest compiled and minified JavaScript -->
   </head>
   <body>


<?php include 'inc/header.php'; ?>

<!--Img superior-->
<div class="container-fluid sinpadding margen-sup-b">
  <div class="row sinpadding">
    <div class="col-lg-12 sinpadding"> 
      <img src="img/rec/SDD.png" class="img-responsive" alt="">
    </div>
  </div>
</div>
<!--End Img superior-->

</br></br>
<div class="container margen-sup">
	<!-- <div class="row"> -->
		<!-- <div class="col-sm-12 text-center"> -->
         <!-- <section class="border flat gradient press"> -->
            <!-- <button id="bt-steel">ACRÍLICOS</button> -->
            <!-- <button id="bt-o100">POLIACRÍLICOS</button> -->
            <!-- <button id="bt-r101">POLICARBONATOS</button> -->
        <!-- </section> -->
    <!-- </div> -->
		<!-- </div> -->
    <!-- </br></br> -->
		
    <!-- <div class="row"> -->
<!--</div> -->
</br></br></br></br>

        <div class="col-sm-12 col-md-6">
      <!--<div class="col-sm-12 col-md-7 col-md-offset-1"> -->
           <h3>RESPALDO SDD</h3> 
        <!--<ul class="list-group">
            <li class="list-group-item">Lamina Galvanizada</li>
            <li class="list-group-item">Lamina Negra</li>
        </ul> -->
        <br/> 
        <p class="text-justify text-indent "><br/>
        Un SDD (unidad de estado sólido) es una nueva generación de dispositivos de almacenamiento que se emplea en equipos. Las unidades SSD almacenan los datos mediante una memoria basada en flash, que es mucho más rápida que los discos duros tradicionales a los que han venido a sustituir. Las unidades SSD tampoco tienen piezas móviles, por lo que actualizarlas a una es una excelente manera de acelerar su ordenador y hacerlo más resistente. Aprenda cómo funcionan las unidades SSD y cómo mantenerlas optimizadas con software de mejora del rendimiento.
        Las unidades SSD almacenan los datos de forma permanente dentro de un circuito integrado, normalmente mediante una memoria flash. La memoria flash dentro de una SSD significa que los datos se escriben, se transfieren y se borran de forma electrónica y silenciosa: las SSD no tienen las partes móviles que se encuentran dentro de las unidades de disco duro mecánicas (HDD). Sin partes móviles, las SSD son rápidas y silenciosas, pero tienen un precio elevado en comparación con las HDD.
    
        </p>

      

        </div> 

        <div class="col-sm-12 col-md-6">
<!--Slider-->

</br></br>
<div id="carousel-example-generic" class="carousel slide pull-right" data-ride="carousel"  data-interval="2500">
  <!-- Indicators -->
 
  <!-- Wrapper for slides -->

  <div class="carousel-inner" role="listbox">   
    <div class="item active">
      <img src="img/rec/SSD.jpg" alt="...">
    </div>
    
  </div> 
  
  <!-- Controls -->
</div>


<!--<div class="col-sm-12 col-md-7 col-md-offset-1"> -->
 </div>  
    <?php include 'inc/catalog-cotizar.php'; ?> 
</div>
<!--End Slider-->
</div>

<?php include 'inc/footer.php'; ?>

<?php include 'inc/footer_common.php'; ?>

     
   </body>
   </html>